<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="append"
     targetNamespace="http://xmlns.oracle.com/SOA_TST/EVENT/append"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/SOA_TST/EVENT/append"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://www.example.org"
    >
    <plnk:partnerLinkType name="append">
        <plnk:role name="appendProvider" portType="client:append"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/SOA_TST/EVENT/append" schemaLocation="../Schemas/append.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="oramds:/apps/OSB/MDS/Schemas/event.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="appendRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="append">
        <wsdl:operation name="process">
            <wsdl:input message="client:appendRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
